ALTER TABLE `site_appearance_settings` ADD `header_subtitle` text DEFAULT '流畅、克制、持续更新的技术写作' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_1_label` text DEFAULT '首页' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_1_href` text DEFAULT '/' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_2_label` text DEFAULT '归档' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_2_href` text DEFAULT '/blog' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_3_label` text DEFAULT '搜索' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `nav_link_3_href` text DEFAULT '/search' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_kicker` text DEFAULT '云端记录' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_title` text DEFAULT '把工程判断写清楚，把技术细节写漂亮。' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_intro` text DEFAULT '这里记录 Cloudflare、前端工程、调试过程和系统设计里那些值得反复回看的瞬间。界面会继续打磨，但内容先要足够清晰、足够耐读。' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_primary_label` text DEFAULT '进入归档' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_primary_href` text DEFAULT '/blog' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_secondary_label` text DEFAULT '站内搜索' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_secondary_href` text DEFAULT '/search' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_signal_label` text DEFAULT 'Scene Depth' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_signal_heading` text DEFAULT '首页会跟着你的视线轻轻转一下' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_signal_copy` text DEFAULT '不是把页面做得很吵，而是只让首屏层次、信息胶囊和按钮反馈更有呼吸感。' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_topic_text` text DEFAULT 'Cloudflare · 前端工程 · 架构细节' NOT NULL;
ALTER TABLE `site_appearance_settings` ADD `hero_writing_text` text DEFAULT '慢一点，但尽量长期有效。' NOT NULL;
